language: go

go:
  - "1.10.x"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

deploy:
  provider: releases
  api_key:
    secure: J7qd4LK5iz7YvZI36m39sGSyhOzwkAXC8aeKrmsQiFTsQIp0BxHyYnHFJN0cM7sZhi2F4+Uv+RE3MIK/qKdb4HWS2lBOc0Ckl0jqoGeldnnCPGb7ZJ/SQmiNieh5p2vOyvrndzsilvOrow6QuJc0xy3Lqd5Ki1pgT3qXVDB5bFRLEb/btOhwfg9b61+sAI5aj1CIn2WKYmBNlr9HDko45HokH65PJBUQk1DiWqwWQ6McnDlZQnMA5JysjDPRdsORnNo+1C63t4RbL6l4doKqsbiRhaux861B4/75M40+JvYdtwz6EOKsj58gViiHN6upmTwJxPESm9okU1SEHlCdUDb8a9NDY3v2wqCk1UoEAtG8+ys/TgG8Qi4hKbX5eNOJr8Q9o0W+ZDrJS134wwoo+HhA+1SOizRA2ODvfdXRLLF0nDdTYcVYkdhaEh3zPjjB4NRLLpN9NWDuGei0gWGUEBeopzbH8fPMRrATpYTtgvBEYVOQP+dKvH3ORMNl/vkLBmFBZpBQeUxvuhBQ6+cUclBMtu1w0sqdRGgJBUIRHRtF3vyaaGF1wslpKuUGvQYCvBV7ip7N2neSCvLjea+cDJv5RLRZ1KizXqvDKa7SxQIiAwz95wC7lx0NjJpCPY8fU7FPP3fvyxOJ1lJq9bG+h0A03IeQUwQG9WGi2hxDIJ0=
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true
